#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
This file is part of OpenSesame Survey Manager

OpenSesame Survey Manager is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenSesame Survey Manager is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Refer to <http://www.gnu.org/licenses/> for a copy of the GNU General Public License.

@author Bob Rosbag
"""

from __future__ import division
from __future__ import unicode_literals
import sys
from PyQt4 import QtGui
from libquestionnairemanager.questionnairemanager_ui import QuestionnaireManagerUI

def main():
    app = QtGui.QApplication(sys.argv)
    win = QuestionnaireManagerUI()
    win.show()
    sys.exit(app.exec_())
                
if __name__ == "__main__":
    main()